import * as PIXI from 'pixi.js';


const STYLE = new PIXI.TextStyle({
    fontFamily: 'Iosevka, Courier New, monospace',
    fill: 'white',
    fontSize: 12,
    padding: 2,
    lineHeight: 20
});
const MAX_MSGS = 25;

/**
 * The Log represents a view of messages generated by the game.
 * The game uses the log to append messages describing events in the game,
 * e.g. "You ate the mouse".
 */
class Log {
    private _stage: PIXI.Container = new PIXI.Container();
    private _count: number = 0;
    private _text: PIXI.Text;

    constructor() {
        this._text = new PIXI.Text('', STYLE);
        this._text.x = 10
        this._stage.addChild(this._text);
        const line = new PIXI.Graphics();
        line.lineStyle(2, 0xAAAAAA, 1);
        line.moveTo(0, 0);
        line.lineTo(0, 600);
        line.x = 310;
        line.y = -10;
        this._stage.addChild(line);
    }

    /**
     * In order to be able to see the log messages, the log needs to be placed
     * somewhere in the stage. This function does that.
     * 
     * @param stage the stage to add the log to
     * @param x the x position to place it
     * @param y the y position to place it
     */
    addTo(stage: PIXI.Container, x?: number, y?: number) {
        stage.addChild(this._stage);
        if (x) this._stage.x = x;
        if (y) this._stage.y = y;
    }

    /**
     * Add a new message to the log.
     * 
     * @param msg the message to append to the log
     */
    addMsg(msg: string) {
        msg += '\n';
        if (this._count < MAX_MSGS) {
            this._count++;
            this._text.text = this._text.text + msg;
        } else {
            const text = this._text.text;
            this._text.text = text.substring(text.indexOf('\n') + 1) + msg;
        }
    }
}
export default Log;